version: "3.8"

services:
  db:
    image: postgres:15
    container_name: go-backend-user-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    ports:
      - "5433:5432"

  app:
    build: .
    container_name: go-backend-user-app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: users_db
    depends_on:
      - db
    ports:
      - "3000:3000"
